apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: crew-ai-test25092401
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: crew-ai-test25092401
  name: crew-ai-test25092401
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: crew-ai-test25092401
