apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: crew-ai-test25092401
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/crew-ai-test25092401:f1063c6adb027567c928f8731c5ff01626fbf70a@sha256:052d283258b0d8a703f4b1b4e98be59404ab0f3cd680f30ca758179277773880 # use pre-built to bootstrap
          name: app-inference
